# Generated by Django 3.1.12 on 2025-01-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_owner', models.CharField(max_length=200)),
                ('process_scope', models.TextField()),
                ('primary_threats', models.TextField()),
                ('critical_assets', models.TextField()),
                ('vulnerabilities', models.TextField()),
                ('asset_description', models.TextField()),
                ('likelihood', models.CharField(max_length=50)),
                ('impact', models.CharField(max_length=50)),
                ('residual_risk', models.CharField(max_length=50)),
                ('existing_controls', models.TextField()),
                ('additional_controls', models.TextField()),
                ('review_frequency', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
