# Generated by Django 3.1.12 on 2025-02-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VTResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_url', models.URLField(max_length=2000)),
                ('malicious', models.IntegerField(default=0)),
                ('suspicious', models.IntegerField(default=0)),
                ('harmless', models.IntegerField(default=0)),
                ('undetected', models.IntegerField(default=0)),
                ('timeout', models.IntegerField(default=0)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'VT_Result',
            },
        ),
    ]
